name: example
description: A new Flutter project.

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter

  disk_lru_cache:
    path: ../

  http:
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
