name: disk_lru_cache
description: Disk lru cache for flutter.
version: 1.0.0
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/best-flutter/disk_lru_cache



environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.5"


dependencies:
  flutter:
    sdk: flutter
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http:

flutter:
